# Modèles du Fake news

Sujet d'ARE DYNAMIC 2018 (Jenny Ogolo, Aya SADOUKI, Ruxue ZENG)

## Introduction

Considérons un ensemble donné d'**individus** que l'on appelera **population**. Chacun de ces individus possède une **opinion binaire** face à un fake news. Naturellement, nous pouvons nous attendre à ce que l'opinion d'un individu donné évolue en fonction des **rencontres** faites avec d'autres individus, par contact physique (que l'on appelle les **voisins** , ou à distance (qu'ils sont appartiennent dans un même **réseau**).

Dans ce contexte, une question émerge principalement :

* Comment évolueront les opinions des individus au cours du temps ?

Dans la première partie de cette mpdèle, nous allons étudier ce modèle en particulier : le **modèle du fake news par contact physique**. Ce modèle effectue les deux hypothèses suivantes :

* L'opinion d'un individu $ i $ est une valeur entier réel ( $ 0 $ ou $ 1 $ ), que nous noterons $ op_i $.

* chaque individu possède une conviction que nous notrerons $ p_i $ (une valeur réel comprise entre $ 0 $ et $ 1 $ inclus)

* Le premier mise à jour consiste à faire évoluer la conviction d'un individu $ i $, lorsqu'il rencontre un individu $ j $ (ou un groupe d'individus en fonction des trois paramètres:

    * l'influence de la force de persuasion $ fp_i $, caractéristique d"un individu, une valeur compris entre $ 0 $ et $ 1 $ inclus, $ p_i $ évolue lorsque $  fp_i $ < $  fp_j $ en appliquant la formule: $ p_i \leftarrow p_i + fp_i  \cdot ( p_j - p_i ) $
    * l'influence du voisinage en appliquant $ p_i \leftarrow p_i + \mu \cdot ( p_j - p_i ) $  si la discussion a eu lieu qu'entre seulement **2 personnes**, **sinon**,l'agent $ i $ adopte la conviction de la majorité.
    * la crédibilité du news $ c_news $ : une valeur réel aléatoire comprise entre $ 0 $ et $ 1 $, influence $ p_i $ de façon suivante: $ p_i \leftarrow p_i + \lambda \cdot ( c - p_i ) $
    
* Le mise à jour de l'opinion consiste à faire évoluer l'opinion d'un individu en fonction de sa nouvelle conviction: if $ p_i  > 0.5 , $ $ op_i $ change. 

Où $ \mu $ est appelé le **paramètre de la force de persuasion**. Ce paramètre permet de contrôler la vitesse de convergence des opinions. Sa valeur est comprise entre $ 0 $ et $ 0.5 $.

Où $ \lambda $ est appelé le **paramètre de la .....................**. Ce paramètre permet de contrôler la vitesse de convergence des opinions. Sa valeur est comprise entre $ 0 $ et $ 0.5 $.




## Initialisation

Nous initialisons une matrice de $ N*N $ individus, et un dictionaire qui associe à chaque individu un tuple sous la forme $ dict $ {$ i:(op,dejavu,fp,p) $}

In [44]:
import numpy as np

def init_systeme(N):
    """cet algorithme crée un groupe de population sous la forme d'une matrice de taille N, et un dictionnaire qui associe
    à chaque individu un tuple sous la forme dict{i:(op,dej_vu,fp,p)} où 
       op:opinion binaire de l'individu
       dej_vu: l'individu a déja vu ou pas le fake news
       fp: le pouvoir de persuasion de l'individu
       p:la conviction de l'individu """
    Population=np.arange(1,N*N+1).reshape(N,N)
    Dict_pop={str(i):(0,False,fp,0.5) for i in np.arange(1,N*N+1) 
        for fp in np.random.uniform(low=0.0, high=1.0, size=(N*N))}
        
    return Dict_pop


N=5
print("Nb_Pop=",N*N)
print("Dict_pop=",init_systeme(N))

Nb_Pop= 25
Dict_pop= {'15': (0, False, 0.3959284740558925, 0.5), '19': (0, False, 0.7991600591755668, 0.5), '18': (0, False, 0.06662639270895288, 0.5), '13': (0, False, 0.4862908560972029, 0.5), '3': (0, False, 0.294896158197832, 0.5), '20': (0, False, 0.9630988382407265, 0.5), '10': (0, False, 0.42638419523308746, 0.5), '25': (0, False, 0.9967593005115281, 0.5), '11': (0, False, 0.058940446039987826, 0.5), '17': (0, False, 0.13825666232104572, 0.5), '22': (0, False, 0.9158127767524995, 0.5), '24': (0, False, 0.43556273159924097, 0.5), '4': (0, False, 0.9729946010768747, 0.5), '21': (0, False, 0.7427652096309061, 0.5), '2': (0, False, 0.9035735797055665, 0.5), '8': (0, False, 0.5154687324629756, 0.5), '9': (0, False, 0.15766347604953102, 0.5), '1': (0, False, 0.20918104376209878, 0.5), '7': (0, False, 0.7208961741030142, 0.5), '14': (0, False, 0.5405317178431224, 0.5), '5': (0, False, 0.04569957239493139, 0.5), '16': (0, False, 0.17089374892871378, 0.5), '12': (0, False, 0.404006812287

In [45]:
def init_sys_avec_malv(N):
    
    Pop=init_systeme(N)
    L= np.random.randint(low=0, high=N*N, size=6,dtype=int)
    for e in L:
        Pop[str(e)]=(1,True,0.9,0.8)
    
    return Pop

print("Pop_av_malv=",init_sys_avec_malv(N))
    

Pop_av_malv= {'0': (1, True, 0.9, 0.8), '15': (0, False, 0.6754321717464348, 0.5), '19': (0, False, 0.08875141971871636, 0.5), '18': (0, False, 0.8821336838915971, 0.5), '13': (1, True, 0.9, 0.8), '3': (0, False, 0.7121427562417336, 0.5), '20': (0, False, 0.38822457237333285, 0.5), '10': (0, False, 0.3142434055878508, 0.5), '25': (0, False, 0.12421962658223995, 0.5), '11': (0, False, 0.4466383554641493, 0.5), '17': (0, False, 0.1738171449809195, 0.5), '22': (1, True, 0.9, 0.8), '24': (1, True, 0.9, 0.8), '4': (0, False, 0.357861936890312, 0.5), '21': (0, False, 0.27489168101421224, 0.5), '2': (0, False, 0.47010852978004636, 0.5), '8': (0, False, 0.5315820075294541, 0.5), '9': (0, False, 0.7237980349442641, 0.5), '1': (1, True, 0.9, 0.8), '7': (0, False, 0.2744168268797814, 0.5), '14': (0, False, 0.11208770420440584, 0.5), '5': (0, False, 0.7223621925249547, 0.5), '16': (0, False, 0.7332244463419784, 0.5), '12': (0, False, 0.031814196092795566, 0.5), '23': (0, False, 0.4509824528291475,

## Contact physique

### Influence de la force de persuasion

In [46]:
import numpy as np
Dict_pop=init_sys_avec_malv(N)


def force_de_persuasion(x, y, Dict_pop):
    """Rule to use to update the opinions."""
    
    #modification du paramètre fpx en fonction de la force de persuasion de y et vice versa.
    
    opx,dej_vux,fpx,px=Dict_pop[x]
    opy,dej_vuy,fpy,py=Dict_pop[y]
    if fpx>fpy:
        py=py+fpy*(px-py)
    elif fpy>fpx:
        px=px+fpx*(py-px)
                
    Dict_pop[x]=(opx,dej_vux,fpx,px)
    Dict_pop[y]=(opy,dej_vuy,fpy,py)
    
    return Dict_pop


In [116]:
def selection_voisinage(Matrice,i):
    '''Sélection aléatoire des voisinages d'un individu
    '''
    Ma=[]
    n=1  #numéro de la ligne

    if i//N==0:
        Ma.append([0,0,0])
        
    for l in Matrice:
        if (n==(i//N) or n==(i//N+1) or n==(i//N+2)) and (i%N!=0):
                if (i%N!=1) and (i%N!=0):
                    Ma.append([l[i%N-2],l[i%N-1],l[i%N]])
                    n=n+1
                elif (i%N==1):
                    Ma.append([0,l[i%N-1],l[i%N]])
                    n=n+1
        elif (n==(i//N-1) or n==(i//N) or n==(i//N+1)) and (i%N==0):
            Ma.append([l[i%N-2],l[i%N-1],0])
            n=n+1
            
        else:
            n=n+1
            
    if i//N==(N-1):
        Ma.append([0,0,0])
    
    A=np.mat(Ma)
    return A

Population=np.arange(1,N*N+1).reshape(N,N)
print(Population)
print(selection_voisinage(Population,1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[0 0 0]
 [0 1 2]
 [0 6 7]]


4