**Influence de la crédibilité de la news sur p**

In [39]:
#numpy.random.choice(liste(ou entier) , taille de l'array , replace=False pour pas avoir deux fois la meme valeur , proba)

import numpy as np
import random as rd


news = np.random.random_sample()
print('Crédibilité de l\'info:',news)

def influ_credib_news(news,p):
    #news: crédibilité de la news
    #p: param déterminant le chgt ou non de l'opinion    
    i = p
    i = i+news*(news-i)
    return i

print(influ_credib_news(0.8,0.5))

Crédibilité de l'info: 0.5887391057618591
0.74


**Influence du voisinage sur p**

In [30]:
"""N=15 #nombre de membres du réseau discussion physique
#description d'un agent : (nom,opinion,deja_vu,persuasion,chgt_opinion)
Reseau_discu={str(k):(0,False,fp,0.5) for k in range(N) for fp in np.random.uniform(low=0.0, high=1.0,size=N)}
Noms_reseau_discu=[str(k) for k in range(N)]

size = int(np.random.choice(range(2,10)))
Discu = np.random.choice(Noms_reseau_discu,size,replace=False)
print('Membres de la discussion',Discu)

def matrice_discu(L,reseau):
    matrice=np.matrix([['00','00','00'],['00','00','00'],['00','00','00']])
    i=0
    j=0
    for (nom,(opinion,deja_vu,persu,p)) in reseau.items():
        if nom in L:
            matrice[i,j]=nom
            if j!=2:
                j=j+1
            elif j==2:
                j=0
                i=i+1
    return matrice
    
print('Matrice discussion :\n',matrice_discu(Discu.copy(),Reseau_discu))

Test_reseau=[(str(k),np.random.choice([0,1]),np.random.choice([False,True]),np.random.random_sample(),np.random.random_sample()) for k in range(N)]
print('Réseau aléatoire :',Test_reseau)

def influ_voisinage(discussion,reseau):
    
    P=[]    #liste des p (conviction) des agents de la discussion
    for listes in discussion:
        for k in listes:
            for (nom,opinion,deja_vu,persu,p) in reseau:
                if k == str(nom):
                    if deja_vu:
                        P.append(p)
    plus_convaincu=max(P)     #p du plus convaincu
    moins_convaicnu=min(P)    #p du moins convaincu
    pi=0.5                    #current conviction
    Pi=[]                     #list of the current convictions
    for listes in discussion:
        for k in listes:
            for (nom,opinion,deja_vu,persu,p) in reseau.items():
                if k == str(nom):
                    pi=p
                    if pi<plus_convaincu:
                        pi=pi+((plus_convaincu-pi)/2)
                    if pi>moins_convaincu:
                        pi=pi+((moins_convaincu-pi)/2)
                    Pi.append(nom,pi)
    for (name,pi) in Pi:
        for (nom,opinion,deja_vu,persu,p) in reseau:
            if name == str(nom):
                p=pi
    return reseau

print(influ_voisinage(matrice_discu(Discu.copy()),Test_reseau))"""

"N=15 #nombre de membres du réseau discussion physique\n#description d'un agent : (nom,opinion,deja_vu,persuasion,chgt_opinion)\nReseau_discu={str(k):(0,False,fp,0.5) for k in range(N) for fp in np.random.uniform(low=0.0, high=1.0,size=N)}\nNoms_reseau_discu=[str(k) for k in range(N)]\n\nsize = int(np.random.choice(range(2,10)))\nDiscu = np.random.choice(Noms_reseau_discu,size,replace=False)\nprint('Membres de la discussion',Discu)\n\ndef matrice_discu(L,reseau):\n    matrice=np.matrix([['00','00','00'],['00','00','00'],['00','00','00']])\n    i=0\n    j=0\n    for (nom,(opinion,deja_vu,persu,p)) in reseau.items():\n        if nom in L:\n            matrice[i,j]=nom\n            if j!=2:\n                j=j+1\n            elif j==2:\n                j=0\n                i=i+1\n    return matrice\n    \nprint('Matrice discussion :\n',matrice_discu(Discu.copy(),Reseau_discu))\n\nTest_reseau=[(str(k),np.random.choice([0,1]),np.random.choice([False,True]),np.random.random_sample(),np.rand

In [18]:
#description d'un agent : nom:(opinion,deja_vu,force_de_persuasion,conviction)
N = 25      #nombre de membres du réseau discussion physique
N_1dim = 5  #nombre de membres du réseau sur une dimension (racine de N)

#initialisation :
Reseau_discu={str(k):(0,False,fp,0.5) for k in range(1,N+1) for fp in np.random.uniform(low=0.0, high=1.0,size=N)}
Noms_reseau_discu=[k for k in range(N)]

"""size = int(np.random.choice(range(2,10)))
Liste_membres_discu = np.random.choice(Noms_reseau_discu,size,replace=False)
print('Membres de la discussion',Liste_membres_discu)""""

#Réseau à valeurs quelconques (au milieu de la simulation par exemple)
Test_reseau={str(k):(np.random.choice([0,1]),np.random.choice([False,True]),np.random.random_sample(),np.random.random_sample()) for k in range(1,N+1)}
print('Réseau aléatoire :',Test_reseau)

#Représentation des agents en 2 dimensions (sur une matrice) :
Agents=np.arange(1,N_1dim*N_1dim+1).reshape(N_1dim,N_1dim)
print('Agents :\n',Agents)

Membres de la discussion [23 10 12 17  8 16  4  2]
Réseau aléatoire : {'17': (1, False, 0.9042574864519366, 0.25144352017936544), '11': (1, False, 0.7233288069598902, 0.9005134129598105), '9': (1, True, 0.7982143247703694, 0.8088303170772944), '5': (0, True, 0.7903717921093343, 0.09546070276936625), '12': (1, True, 0.6174189632905707, 0.9364229162869907), '3': (0, True, 0.7513024250420219, 0.7736451673991783), '24': (0, False, 0.7865398451222205, 0.4652299979420932), '22': (1, False, 0.27905485045489375, 0.4766069298664686), '16': (0, False, 0.1780169033225626, 0.6663588700792893), '8': (1, True, 0.45827563620857004, 0.5353125854060017), '13': (0, False, 0.3512935091348638, 0.8694769733609649), '21': (1, False, 0.35734728630224355, 0.9594241620996065), '23': (0, True, 0.9291835554953728, 0.8219467313463689), '19': (0, False, 0.8431313485434869, 0.3857674922403137), '15': (0, True, 0.043207684403046676, 0.30416844561528755), '10': (0, True, 0.28314218481591247, 0.4674377146361638), '20'

In [46]:
#Sélection d'un agent et de son voisinage pour établir un discussion
def selection_voisinage(Matrice,i):
    '''Sélection aléatoire des voisinages d'un individu
    '''
    Ma=[]
    n=1  #numéro de la ligne

    if i//N_1dim==0:
        Ma.append([0,0,0])
        
    for l in Matrice:
        if (n==(i//N_1dim) or n==(i//N_1dim+1) or n==(i//N_1dim+2)) and (i%N_1dim!=0):
                if (i%N_1dim!=1) and (i%N_1dim!=0):
                    Ma.append([l[i%N_1dim-2],l[i%N_1dim-1],l[i%N_1dim]])
                    n=n+1
                elif (i%N_1dim==1):
                    Ma.append([0,l[i%N_1dim-1],l[i%N_1dim]])
                    n=n+1
        elif (n==(i//N_1dim-1) or n==(i//N_1dim) or n==(i//N_1dim+1)) and (i%N_1dim==0):
            Ma.append([l[i%N_1dim-2],l[i%N_1dim-1],0])
            n=n+1
            
        else:
            n=n+1
            
    if i//N_1dim==(N_1dim-1):
        Ma.append([0,0,0])
    
    A=np.mat(Ma)
    return A

Population=np.arange(1,N_1dim*N_1dim+1).reshape(N_1dim,N_1dim)
Mat_discu=selection_voisinage(Population,1)
print('Population :\n',Population)
print('Matrice discussion :\n',selection_voisinage(Population,1))

Population :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Matrice discussion :
 [[0 0 0]
 [0 1 2]
 [0 6 7]]


In [64]:
#Modification du paramètre px en fonction de la force de persuasion de y et vice versa :
def force_persu(x, y, reseau):
        
    opx,deja_vux,fpx,px=reseau[str(x)]
    opy,deja_vuy,fpy,py=reseau[str(y)]
    if fpx>fpy:
        py=py+fpy*(px-py)
    elif fpy>fpx:
        px=px+fpx*(py-px)
                
    reseau[str(x)]=(opx,deja_vux,fpx,px)
    reseau[str(y)]=(opy,deja_vuy,fpy,py)
    
    return reseau

print(force_persu(1,7,Reseau_discu))


#Influence du voisinage :
    # si 2 personnes, force persu. Sinon, moyenne des p pondérée des fp, puis si (pi-moy)>seuil, pi ne change pas, sinon pi->moy
def influ_voisinage(mat_discu,reseau,seuil):
    
    P=[]   #liste des convictions des membres de la discussion
    F=[]   #liste des forces de persuasion des membres de la discussion
    N=[]   #liste des noms des membres de la discussion
    a_central=mat_discu[1,1] #agent central de la matrice discu
    i=0
    
    for k in np.nditer(mat_discu):
        if k!=0:
            op_k,deja_k,fp_k,p_k=reseau[str(k)]
            N.append(int(k))
            P.append(p_k)
            F.append(fp_k)
    print(N)
            
    if len(N)==2:
        reseau=force_persu(N[0],N[1],reseau)
    else:
        for a in N:
            other_p=P[0:a]+P[a+1:len(P)]
            other_fp=F[0:a]+F[a+1:len(F)]            
            moyenne=np.average(other_p,weights=other_fp)
            print(moyenne)
    return None
influ_voisinage(Mat_discu,Test_reseau,0.5)

{'17': (0, False, 0.7373112812573912, 0.5), '11': (0, False, 0.4214337568566501, 0.5), '9': (0, False, 0.5387831094461808, 0.5), '5': (0, False, 0.5916401359145931, 0.5), '12': (0, False, 0.5898682074588764, 0.5), '3': (0, False, 0.16642994276408507, 0.5), '24': (0, False, 0.7235093909153378, 0.5), '22': (0, False, 0.9679502731185755, 0.5), '16': (0, False, 0.9897359997448446, 0.5), '8': (0, False, 0.8061358499503103, 0.5), '13': (0, False, 0.9902305164783051, 0.5), '21': (0, False, 0.11284259443553102, 0.5), '23': (0, False, 0.4087701843569005, 0.5), '19': (0, False, 0.6037363037144746, 0.5), '15': (0, False, 0.6157181290730674, 0.5), '10': (0, False, 0.9100034210586934, 0.5), '20': (0, False, 0.23717221338010797, 0.5), '1': (0, False, 0.44760635933438875, 0.5), '7': (0, False, 0.3816041299284264, 0.5), '14': (0, False, 0.1861742593315049, 0.5), '2': (0, False, 0.9539797011478132, 0.5), '18': (0, False, 0.39730754165534454, 0.5), '6': (0, False, 0.3703585668431252, 0.5), '4': (0, Fals

In [62]:
L = [0,1,2,3,4,5]
M = L[0:2]+L[3:6]
print(M)



[0, 1, 3, 4, 5]
