**Influence de la crédibilité de la news sur p**

In [2]:
#numpy.random.choice(liste(ou entier) , taille de l'array , replace=False pour pas avoir deux fois la meme valeur , proba)

import numpy as np
import random as rd


news = np.random.random_sample()
print('Crédibilité de l\'info:',news)

def influ_credib_news(news,p):
    #news: crédibilité de la news
    #p: param déterminant le chgt ou non de l'opinion    
    i = p
    i = i+news*(news-i)
    return i

print(influ_credib_news(0.8,0.5))

Crédibilité de l'info: 0.9697157292245362
0.74


**Influence du voisinage sur p**

In [3]:
"""N=15 #nombre de membres du réseau discussion physique
#description d'un agent : (nom,opinion,deja_vu,persuasion,chgt_opinion)
Reseau_discu={str(k):(0,False,fp,0.5) for k in range(N) for fp in np.random.uniform(low=0.0, high=1.0,size=N)}
Noms_reseau_discu=[str(k) for k in range(N)]

size = int(np.random.choice(range(2,10)))
Discu = np.random.choice(Noms_reseau_discu,size,replace=False)
print('Membres de la discussion',Discu)

def matrice_discu(L,reseau):
    matrice=np.matrix([['00','00','00'],['00','00','00'],['00','00','00']])
    i=0
    j=0
    for (nom,(opinion,deja_vu,persu,p)) in reseau.items():
        if nom in L:
            matrice[i,j]=nom
            if j!=2:
                j=j+1
            elif j==2:
                j=0
                i=i+1
    return matrice
    
print('Matrice discussion :\n',matrice_discu(Discu.copy(),Reseau_discu))

Test_reseau=[(str(k),np.random.choice([0,1]),np.random.choice([False,True]),np.random.random_sample(),np.random.random_sample()) for k in range(N)]
print('Réseau aléatoire :',Test_reseau)

def influ_voisinage(discussion,reseau):
    
    P=[]    #liste des p (conviction) des agents de la discussion
    for listes in discussion:
        for k in listes:
            for (nom,opinion,deja_vu,persu,p) in reseau:
                if k == str(nom):
                    if deja_vu:
                        P.append(p)
    plus_convaincu=max(P)     #p du plus convaincu
    moins_convaicnu=min(P)    #p du moins convaincu
    pi=0.5                    #current conviction
    Pi=[]                     #list of the current convictions
    for listes in discussion:
        for k in listes:
            for (nom,opinion,deja_vu,persu,p) in reseau.items():
                if k == str(nom):
                    pi=p
                    if pi<plus_convaincu:
                        pi=pi+((plus_convaincu-pi)/2)
                    if pi>moins_convaincu:
                        pi=pi+((moins_convaincu-pi)/2)
                    Pi.append(nom,pi)
    for (name,pi) in Pi:
        for (nom,opinion,deja_vu,persu,p) in reseau:
            if name == str(nom):
                p=pi
    return reseau

print(influ_voisinage(matrice_discu(Discu.copy()),Test_reseau))"""

"N=15 #nombre de membres du réseau discussion physique\n#description d'un agent : (nom,opinion,deja_vu,persuasion,chgt_opinion)\nReseau_discu={str(k):(0,False,fp,0.5) for k in range(N) for fp in np.random.uniform(low=0.0, high=1.0,size=N)}\nNoms_reseau_discu=[str(k) for k in range(N)]\n\nsize = int(np.random.choice(range(2,10)))\nDiscu = np.random.choice(Noms_reseau_discu,size,replace=False)\nprint('Membres de la discussion',Discu)\n\ndef matrice_discu(L,reseau):\n    matrice=np.matrix([['00','00','00'],['00','00','00'],['00','00','00']])\n    i=0\n    j=0\n    for (nom,(opinion,deja_vu,persu,p)) in reseau.items():\n        if nom in L:\n            matrice[i,j]=nom\n            if j!=2:\n                j=j+1\n            elif j==2:\n                j=0\n                i=i+1\n    return matrice\n    \nprint('Matrice discussion :\n',matrice_discu(Discu.copy(),Reseau_discu))\n\nTest_reseau=[(str(k),np.random.choice([0,1]),np.random.choice([False,True]),np.random.random_sample(),np.rand

In [5]:
#description d'un agent : nom:(opinion,deja_vu,force_de_persuasion,conviction)
N = 25      #nombre de membres du réseau discussion physique
N_1dim = 5  #nombre de membres du réseau sur une dimension (racine de N)

#initialisation :
Reseau_discu={str(k):(0,False,fp,0.5) for k in range(1,N+1) for fp in np.random.uniform(low=0.0, high=1.0,size=N)}
Noms_reseau_discu=[k for k in range(N)]

"""size = int(np.random.choice(range(2,10)))
Liste_membres_discu = np.random.choice(Noms_reseau_discu,size,replace=False)
print('Membres de la discussion',Liste_membres_discu)"""

#Réseau à valeurs quelconques (au milieu de la simulation par exemple)
Test_reseau={str(k):(np.random.choice([0,1]),np.random.choice([False,True]),np.random.random_sample(),np.random.random_sample()) for k in range(1,N+1)}
print('Réseau aléatoire :',Test_reseau)

#Représentation des agents en 2 dimensions (sur une matrice) :
Agents=np.arange(1,N_1dim*N_1dim+1).reshape(N_1dim,N_1dim)
print('Agents :\n',Agents)

Réseau aléatoire : {'1': (0, False, 0.7203084047432925, 0.521704674328691), '2': (0, True, 0.002125476242240243, 0.4295194980093868), '3': (0, True, 0.7229085797118171, 0.7364687587049173), '4': (1, False, 0.11893021512502377, 0.802996996017149), '5': (0, False, 0.8231862734871533, 0.255363990414758), '6': (0, False, 0.23964161006032014, 0.8616793168846528), '7': (0, True, 0.4177350888764817, 0.9577695516502415), '8': (1, True, 0.11723050037486094, 0.4282140912755086), '9': (1, True, 0.6469343057672746, 0.2143484909696476), '10': (1, True, 0.7093414763576475, 0.9083845859360067), '11': (1, False, 0.351389280855366, 0.14314119769910383), '12': (0, True, 0.6804718801384179, 0.2762931852648042), '13': (0, False, 0.32235746744803917, 0.4385703271790683), '14': (0, True, 0.5886082061418879, 0.2363124377415975), '15': (0, True, 0.6919750579032161, 0.8664707410772591), '16': (0, False, 0.15935964581858875, 0.777124362570929), '17': (0, True, 0.0818641574336586, 0.14744808049939861), '18': (1,

In [6]:
#Sélection d'un agent et de son voisinage pour établir un discussion
def selection_voisinage(Matrice,i):
    '''Sélection aléatoire des voisinages d'un individu
    '''
    Ma=[]
    n=1  #numéro de la ligne

    if i//N_1dim==0:
        Ma.append([0,0,0])
        
    for l in Matrice:
        if (n==(i//N_1dim) or n==(i//N_1dim+1) or n==(i//N_1dim+2)) and (i%N_1dim!=0):
                if (i%N_1dim!=1) and (i%N_1dim!=0):
                    Ma.append([l[i%N_1dim-2],l[i%N_1dim-1],l[i%N_1dim]])
                    n=n+1
                elif (i%N_1dim==1):
                    Ma.append([0,l[i%N_1dim-1],l[i%N_1dim]])
                    n=n+1
        elif (n==(i//N_1dim-1) or n==(i//N_1dim) or n==(i//N_1dim+1)) and (i%N_1dim==0):
            Ma.append([l[i%N_1dim-2],l[i%N_1dim-1],0])
            n=n+1
            
        else:
            n=n+1
            
    if i//N_1dim==(N_1dim-1):
        Ma.append([0,0,0])
    
    A=np.mat(Ma)
    return A

Population=np.arange(1,N_1dim*N_1dim+1).reshape(N_1dim,N_1dim)
Mat_discu=selection_voisinage(Population,1)
print('Population :\n',Population)
print('Matrice discussion :\n',selection_voisinage(Population,1))

Population :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Matrice discussion :
 [[0 0 0]
 [0 1 2]
 [0 6 7]]


In [22]:
#Modification du paramètre px en fonction de la force de persuasion de y et vice versa :
def force_persu(x, y, reseau):
        
    opx,deja_vux,fpx,px=reseau[str(x)]
    opy,deja_vuy,fpy,py=reseau[str(y)]
    if fpx>fpy:
        py=py+fpy*(px-py)
    elif fpy>fpx:
        px=px+fpx*(py-px)
                
    reseau[str(x)]=(opx,deja_vux,fpx,px)
    reseau[str(y)]=(opy,deja_vuy,fpy,py)
    
    return reseau



#Influence du voisinage :
    # si 2 personnes, force persu. Sinon, moyenne des p pondérée des fp, puis si (pi-moy)>seuil, pi ne change pas, sinon pi->moy
def influ_voisinage(mat_discu,reseau,seuil):
    
    P=[]   #liste des convictions des membres de la discussion
    F=[]   #liste des forces de persuasion des membres de la discussion
    N=[]   #liste des noms des membres de la discussion
    a_central=mat_discu[1,1] #agent central de la matrice discu
    i=0
    
    for k in np.nditer(mat_discu):
        if k!=0:
            op_k,deja_k,fp_k,p_k=reseau[str(k)]
            N.append(int(k))
            P.append(p_k)
            F.append(fp_k)
            
    if len(N)==2:
        reseau=force_persu(N[0],N[1],reseau)
    else:
        for a in N:
            op_a,deja_a,fp_a,p_a=reseau[str(a)]
            other_p=P[0:a]+P[a+1:len(P)]
            other_fp=F[0:a]+F[a+1:len(F)]            
            moy=np.average(other_p,weights=other_fp)
            if abs(p_a-moy)<seuil:
                p_a=moy
            reseau[str(a)]=(op_a,deja_a,fp_a,p_a)
    
            
    return reseau

print(influ_voisinage(Mat_discu,Test_reseau,0.2))

{'1': (0, False, 0.7203084047432925, 0.6700403071645904), '2': (0, True, 0.002125476242240243, 0.6295951065382434), '3': (0, True, 0.7229085797118171, 0.7364687587049173), '4': (1, False, 0.11893021512502377, 0.802996996017149), '5': (0, False, 0.8231862734871533, 0.255363990414758), '6': (0, False, 0.23964161006032014, 0.6699028376473366), '7': (0, True, 0.4177350888764817, 0.6699028376473366), '8': (1, True, 0.11723050037486094, 0.4282140912755086), '9': (1, True, 0.6469343057672746, 0.2143484909696476), '10': (1, True, 0.7093414763576475, 0.9083845859360067), '11': (1, False, 0.351389280855366, 0.14314119769910383), '12': (0, True, 0.6804718801384179, 0.2762931852648042), '13': (0, False, 0.32235746744803917, 0.4385703271790683), '14': (0, True, 0.5886082061418879, 0.2363124377415975), '15': (0, True, 0.6919750579032161, 0.8664707410772591), '16': (0, False, 0.15935964581858875, 0.777124362570929), '17': (0, True, 0.0818641574336586, 0.14744808049939861), '18': (1, True, 0.998945172