In [3]:
import numpy as np
N=50


Réseaux_sociaux={'Facebook': np.random.randint(low=0, high=N, size=(N-20),dtype=int),
'Twitter': np.random.randint(low=0, high=N, size=(N-30),dtype=int),
'Snap': np.random.randint(low=0, high=N, size=(N-25),dtype=int)}

Réseaux_physiques={'Famille_1': np.random.randint(low=0, high=N, size=(N-20),dtype=int),
'Famille_2': np.random.randint(low=0, high=N, size=(N-30),dtype=int),
'Famille_3': np.random.randint(low=0, high=N, size=(N-25),dtype=int)}


print(Réseaux_sociaux,
      Réseaux_physiques)


{'Snap': array([47, 26,  3, 43, 30, 44, 25, 20,  7, 20, 46, 17, 14,  7, 28, 23, 21,
       18,  0, 31, 26, 23, 42, 42, 22]), 'Twitter': array([41,  1,  4, 48, 22, 26, 18, 40,  8,  4,  3, 47, 34, 22, 47, 30,  0,
       12, 32, 42]), 'Facebook': array([ 9, 12, 12,  9, 39, 45, 17, 36,  4, 42,  5,  3, 47, 40, 17, 27,  1,
       48, 28, 38, 15, 35,  8,  3, 25,  1, 38, 38, 16, 43])} {'Famille_3': array([13, 37, 34, 25, 40, 44,  9, 14, 39,  0, 43, 17,  1, 12,  5, 42, 16,
        3,  6, 15, 34, 11, 25, 41, 16]), 'Famille_1': array([42, 26, 18, 18,  3, 16,  0,  8, 33,  9, 15, 42,  5,  3, 11, 30, 47,
       13, 40, 48, 46, 11, 23,  6, 14, 33, 13,  4, 25,  1]), 'Famille_2': array([29, 10, 47,  7, 30,  0, 19,  4,  1, 45, 37,  2, 10, 44,  3,  5, 37,
       18, 32, 42])}


In [10]:
N=50
state = np.random.randint(low=0, high=N, size=(30),dtype=int)

print(state)

[ 8 35 29 38 34 25 41 45  5 26  6  6 33 38  9 39 49 48 21 13 24 45 48 19
 21 18 33 43 31 31]


In [91]:
import numpy as np

def bounded_update_opinion(x, y, N):
    """Rule to use to update the opinions."""
    
    #modification de l'opinion binaire de x et y en fonction de f, une force de persuasion tirée aléatoirement dans la liste L
    #L étant la liste des forces de persuasion des individus dans N
    
    L= np.random.uniform(low=0.0, high=1.0, size=20)
    for f in np.random.choice(L, size=1):
        print('L=',L)
        print('f:',f)
        if f>0.8:
            x = x + 1
            y = y + 1
            
    return x, y

x=0
y=0
N=15
print(bounded_update_opinion(x, y, N))

L= [0.04331698 0.20747759 0.24346302 0.00793849 0.31579543 0.0440719
 0.8817737  0.77905601 0.7615252  0.04915719 0.61991382 0.53277346
 0.03982765 0.20567201 0.23813469 0.45874799 0.60921883 0.04410686
 0.6539596  0.33861356]
f: 0.20567201194358975
(0, 0)


In [58]:
import numpy as np

N=15
LR={c:(np.random.choice([0,1]),np.random.choice([False,True]),d) for c in range(N) 
    for d in np.random.randint(10,size=N,dtype=int)}
print("LR=",LR)

def crédulité(c1, c2, LR):
    #changement de l'opinion selon la crédulité des agents lorsque les deux agents se rencontrent
    
    op1,dejavu1,créd1=LR[c1]
    op2,dejavu2,créd2=LR[c2]
    if (dejavu1==False):
        if (dejavu2==True):
            dejavu1=True
            op1=op2
    elif dejavu2==False:
        if (dejavu1==True):
            dejavu2=True
            op2=op1

    elif (dejavu1==True) and (dejavu2==True):    
        if créd1>créd2:
            op2=op1
        elif créd1<créd2:
            op1=op2
    
    LR[c1]=(op1,dejavu1,créd1)
    LR[c2]=(op2,dejavu2,créd2)
    
    return LR


print("New_LR=",crédulité(3, 5, LR))

LR= {0: (1, False, 8), 1: (0, True, 9), 2: (1, False, 3), 3: (1, True, 8), 4: (1, True, 2), 5: (0, False, 6), 6: (1, False, 5), 7: (0, True, 2), 8: (1, False, 4), 9: (0, True, 8), 10: (0, False, 7), 11: (0, True, 3), 12: (0, True, 3), 13: (1, False, 9), 14: (0, True, 1)}
New_LR= {0: (1, False, 8), 1: (0, True, 9), 2: (1, False, 3), 3: (1, True, 8), 4: (1, True, 2), 5: (1, True, 6), 6: (1, False, 5), 7: (0, True, 2), 8: (1, False, 4), 9: (0, True, 8), 10: (0, False, 7), 11: (0, True, 3), 12: (0, True, 3), 13: (1, False, 9), 14: (0, True, 1)}


In [65]:
import numpy as np

N=15
L={c:(np.random.choice([0,1]),np.random.choice([False,True]),d,p) for c in range(N) 
    for d in np.random.randint(10,size=N,dtype=int)
   for p in np.random.uniform(low=0.0, high=1.0, size=N)}
print("L=",L)


def crédulité2(c1, c2, L):
    #changement du paramètre p selon la crédulité des agents lorsque les deux agents se rencontrent
    
    op1,dejavu1,créd1,p1=L[c1]
    op2,dejavu2,créd2,p2=L[c2]
    if (dejavu1==False):
        if (dejavu2==True):
            dejavu1=True
            op1=op2
    elif dejavu2==False:
        if (dejavu1==True):
            dejavu2=True
            op2=op1

    elif (dejavu1==True) and (dejavu2==True):    
        if créd1>créd2:
            p1=p1*1.2
        elif créd1<créd2:
            p2=p2*1.2
    
    L[c1]=(op1,dejavu1,créd1,p1)
    L[c2]=(op2,dejavu2,créd2,p2)
    
    return L

print("New_L=",crédulité2(3, 5, L))

L= {0: (0, True, 3, 0.10941012516841098), 1: (0, False, 4, 0.7790528286771261), 2: (0, False, 6, 0.24775531964550424), 3: (1, True, 6, 0.3412269762912836), 4: (1, True, 5, 0.2964076334573622), 5: (1, False, 5, 0.5953053743682637), 6: (0, False, 4, 0.8906507748898553), 7: (0, True, 7, 0.4110297690927137), 8: (0, False, 9, 0.6947254400738011), 9: (1, False, 2, 0.6786613352467503), 10: (1, True, 8, 0.8583449884744441), 11: (1, False, 9, 0.6907464847809386), 12: (0, False, 3, 0.5429280487324437), 13: (1, False, 6, 0.5721949512465833), 14: (0, True, 1, 0.3255145249697673)}
New_L= {0: (0, True, 3, 0.10941012516841098), 1: (0, False, 4, 0.7790528286771261), 2: (0, False, 6, 0.24775531964550424), 3: (1, True, 6, 0.3412269762912836), 4: (1, True, 5, 0.2964076334573622), 5: (1, True, 5, 0.5953053743682637), 6: (0, False, 4, 0.8906507748898553), 7: (0, True, 7, 0.4110297690927137), 8: (0, False, 9, 0.6947254400738011), 9: (1, False, 2, 0.6786613352467503), 10: (1, True, 8, 0.8583449884744441), 11

In [310]:
L=np.random.uniform(low=0, high=5, size=(5,5))
print("L",L)
i=(a,b)
a=3
b=3

def selection_voisinage(Matrice,i):

    Ma=[]
    n=1

    for l in L:
        if n==(a-1) or n==a:
            Ma.append([l[b-2],l[b-1],l[b]])
            n=n+1
        elif n==a+1:
            Ma.append([l[b-2],l[b-1],l[b]])
            return Ma
        else:
            n=n+1
            
    return Ma
print(selection_voisinage(L,i))

L [[2.99937067 4.68460497 1.09947067 4.73791499 4.38815545]
 [0.60923748 3.43459742 4.82505243 4.64768884 3.67605969]
 [1.19799176 4.53956227 0.75835451 0.13762477 0.36142897]
 [0.61339735 4.32563185 1.28235341 0.59008107 2.55366529]
 [0.25218888 3.30565241 2.98443799 1.43199717 2.04590552]]
[[3.434597418240679, 4.825052427276683, 4.647688843138274], [4.539562266347335, 0.758354513417332, 0.13762477458026112], [4.325631846166356, 1.2823534101188234, 0.5900810663187006]]
